
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import java.text.*;
import java.awt.print.*;

public class addacount extends javax.swing.JFrame {
Connection conn=null;
 ResultSet rs=null;
 PreparedStatement po=null;
   
    public addacount() throws SQLException {
        initComponents();
        setTitle("accountant information");
         conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fee","root","");
       Update_table();
    }
     private void Update_table(){
     try {
         String sql="select * from addac";
         po=conn.prepareStatement(sql);
         rs=po.executeQuery();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
     } catch (SQLException ex) {
         Logger.getLogger(addstdnt.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextname = new javax.swing.JTextField();
        jTextgmail = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextcontact = new javax.swing.JTextField();
        addaccount = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addaccount1 = new javax.swing.JButton();
        addaccount2 = new javax.swing.JButton();
        jTextFieldac = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hd-butterflies-vector-wallpaper.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 106, 99, -1));

        name.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 255, 204));
        name.setText("AC_ID");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 20));

        email.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 255, 204));
        email.setText("EMAIL");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 30));

        password.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 255, 204));
        password.setText("PASSWORD");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 204));
        jLabel8.setText("CONTACT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, 30));

        jTextname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 30));
        getContentPane().add(jTextgmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 30));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));

        jTextcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcontactActionPerformed(evt);
            }
        });
        getContentPane().add(jTextcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, 30));

        addaccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addaccount.setText("UPDATE");
        addaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccountActionPerformed(evt);
            }
        });
        getContentPane().add(addaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 180, 30));

        back.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        back.setForeground(new java.awt.Color(204, 0, 0));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 180, -1));

        jTable1.setForeground(new java.awt.Color(255, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 590, 500));

        addaccount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addaccount1.setText("DELETE");
        addaccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccount1ActionPerformed(evt);
            }
        });
        getContentPane().add(addaccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 180, 30));

        addaccount2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addaccount2.setText("ADD ACCOUNT");
        addaccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccount2ActionPerformed(evt);
            }
        });
        getContentPane().add(addaccount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 180, 30));
        getContentPane().add(jTextFieldac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, 30));

        name1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 255, 204));
        name1.setText("NAME");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("SEARCH ACCOUNT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 140, 30));

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 90, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 180, 30));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 80, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/585663098-blue-background-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 880, 570));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ADD ACCOUNT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 110, 40));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ADD ACCOUNT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
            new AdminSection().setVisible(true);
            this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void addaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccountActionPerformed
                    try{
                        String ac_id=jTextFieldac.getText();
                       String namea=jTextname.getText();
                        String emaila=jTextgmail.getText(); 
                         String passa=jPasswordField1.getText(); 
                          String con=jTextcontact.getText(); 
                    String sql="update  addac set AC_ID='"+ac_id+"', NAME='"+namea+"',EMAIL='"+emaila+"',PASSWORD='"+passa+"',CONTACT='"+con+"' where AC_ID='"+ac_id+"'";    
                    po=conn.prepareStatement(sql);
                     po.execute();
       JOptionPane.showMessageDialog(null, "updated");   
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    
                    }Update_table();
                    jTextFieldac.setText("");
                    jTextname.setText("");
       jTextgmail.setText("");
      
       jPasswordField1.setText("");
       jTextcontact.setText("");
    }//GEN-LAST:event_addaccountActionPerformed

    private void jTextcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcontactActionPerformed

    private void addaccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccount1ActionPerformed
        String sql="delete from addac where AC_ID=?";
      try{
          po=conn.prepareStatement(sql);
          po.setString(1,jTextFieldac.getText());
          po.execute();
          JOptionPane.showMessageDialog(null,"deleted");
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }Update_table();
      jTextFieldac.setText("");
        jTextname.setText("");
       jTextgmail.setText("");
      
       jPasswordField1.setText("");
       jTextcontact.setText("");
    }//GEN-LAST:event_addaccount1ActionPerformed

    private void addaccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccount2ActionPerformed
     
        try {
           
           // con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fee","root","");
            String sql="insert into addac(AC_ID,NAME,EMAIL,PASSWORD,CONTACT) values(?,?,?,?,?)";
              po=conn.prepareStatement(sql);
              po.setString(1, jTextFieldac.getText());
            po.setString(2, jTextname.getText());
           
            po.setString(3,jTextgmail.getText());
            po.setString(4,jPasswordField1.getText());
            po.setString(5,jTextcontact.getText());
          
            po.execute();
            JOptionPane.showMessageDialog(null,"Record saved");
             
            
        } catch (SQLException ex) {
            Logger.getLogger(addacount.class.getName()).log(Level.SEVERE, null, ex);
        }Update_table();
        jTextFieldac.setText("");
         jTextname.setText("");
       jTextgmail.setText("");
      
       jPasswordField1.setText("");
       jTextcontact.setText("");
    }//GEN-LAST:event_addaccount2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         try{
            int row=jTable1.getSelectedRow();
            String Table_clicked=(jTable1.getModel().getValueAt(row, 0).toString());
            String sql="select * from addac where AC_ID='"+Table_clicked+"' ";
             po=conn.prepareStatement(sql);
         rs=po.executeQuery();
         
         if(rs.next()){
             String s5=rs.getString("AC_ID");
             jTextFieldac.setText(s5);
             
             String s1=rs.getString("NAME");
             jTextname.setText(s1);
             
              String s2=rs.getString("EMAIL");
            jTextgmail.setText(s2);
             
              String s3=rs.getString("PASSWORD");
            jPasswordField1.setText(s3);
             
              String s4=rs.getString("CONTACT");
            jTextcontact.setText(s4);
         }
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        try{
                  String sql="select * from addac where AC_ID=?";
                  po=conn.prepareStatement(sql);
                  po.setString(1, jTextField1.getText());
                  
                  
                  rs=po.executeQuery();
                  if(rs.next()){
                      String s1=rs.getString("AC_ID");
                      jTextFieldac.setText(s1);
                      
                      String s2=rs.getString("NAME");
                      jTextname.setText(s2);
                      
                      String s3=rs.getString("EMAIL");
                     jTextgmail.setText(s3);
                      
                       String s4=rs.getString("PASSWORD");
                       jPasswordField1.setText(s4);
                       
                        String s5=rs.getString("CONTACT");
                        jTextcontact.setText(s5);
                        
                        
                      
                  }
                  
                    
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldac.setText("");
         jTextname.setText("");
       jTextgmail.setText("");
      
       jPasswordField1.setText("");
       jTextcontact.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      MessageFormat header=new MessageFormat("Report prient");
         MessageFormat footer=new MessageFormat("page{0,number,integer}");
         try {
             jTable1.print(JTable.PrintMode.NORMAL,header,footer);
         } catch (PrinterException ex) {
             Logger.getLogger(addstdnt.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addacount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addacount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addacount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addacount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new addacount().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(addacount.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addaccount;
    private javax.swing.JButton addaccount1;
    private javax.swing.JButton addaccount2;
    private javax.swing.JButton back;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldac;
    private javax.swing.JTextField jTextcontact;
    private javax.swing.JTextField jTextgmail;
    private javax.swing.JTextField jTextname;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
